### ISSUE TITLE
Potential security breach.

### ISSUE THREAD

**Issue by agood-boy** [bkolicoski/ttc-tools#3]
Potential security breach. Google OAuth Key in Url in file [/client_secret_161148289031-vika03qg7061jo7pu65k8e3nnuas6g0b.apps.googleusercontent.com.json](https://github.com/bkolicoski/ttc-tools/tree/master/client_secret_161148289031-vika03qg7061jo7pu65k8e3nnuas6g0b.apps.googleusercontent.com.json)

You should recycle your credenttials immediately and move secrets to environment variables to prevent them being committed to GitHub.

Hope this will be helpful to you！

shout me a coffee ☕️ via [PayPal](https://www.paypal.me/agoodboy)

<a href="https://www.paypal.me/agoodboy">
  <img width="160" height="41" src="https://raw.githubusercontent.com/DWilliames/paddy-sketch-plugin/master/.images/paypal-badge.png" >
</a>

**Comment by bkolicoski** [comment]
Fixed. The file is removed and secrets are rolled.
