### ISSUE TITLE
YouTube Latest videos playlist

### ISSUE THREAD

**Issue by guram13** [bkolicoski/ttc-tools#42]
Hello, I use your website: https://tools.tastethecode.com/youtube-latest
Is it possible to gel link of  YouTube Latest videos playlist? Not just 1 video.

**Comment by guram13** [comment]
For example:
https://www.youtube.com/watch?v=0CTp1a-aCUM #latest video
 ADD  &list= and #channelname                             &list=UULFX6OQ3DkcsbYNE6H8uQQuVA    
https://www.youtube.com/watch?v=0CTp1a-aCUM&list=UULFX6OQ3DkcsbYNE6H8uQQuVA

**Comment by bkolicoski** [comment]
Hey @guram13, as of now that is not possible. There was a pervious request for this as well so once I have the time, I'll try to implement this as well but I make no promises.

**Comment by guram13** [comment]
Ok, thank you.
